### ISSUE TITLE
Why adding z_sqr to sample proportion during rate calculation?

### ISSUE THREAD

**Issue by fralik** [Refefer/propagon#3]
When rate calculation function is called with a confidence interval of 0.95 or 0.9, then you calculate the sample proportion as `let p_t = (x as f32 + z_sqr / 2.) / n_t;`, see https://github.com/Refefer/propagon/blob/7dc6c45a195b612b9b0f1d772f14e291d40ffcfc/src/main.rs#L130
`z_sqr` is also added to `n_t`.

I wonder what is the motivation behind this. I thought that `x` and `n` could be used directly in range calculation.

**Comment by Refefer** [comment]
I believe I'm using the wilson score interval (
https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval)
which provides slightly better bounds than the normal approximation.  I'll
add some tests to confirm that it's behaving the way it should and given
the compiler has improved since this block of code was written, I can
probably just replace the algorithm with a direct translation rather than
all the indirection from manual constant lifting.

**Comment by Refefer** [comment]
Updated with tests.  Thanks for the report and question :)
